site_name: FISI-Curriculum

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences

extra_css:
    - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_FISI_Curriculum

nav:
    - Übersicht: index.md
    - FISI LS 2.6: FISI-LF2_LS2.6.md
    - FISI LS 2.7: FISI-LF2_LS2.7.md
    - FISI LS 2.8: FISI-LF2_LS2.8.md
